# Generated by Django 5.0.6 on 2024-06-15 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catégorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(blank=True, max_length=50, null=True)),
                ('quantité', models.IntegerField(default='0', null=True)),
                ('recevoir_quantité', models.IntegerField(blank=True, default='0', null=True)),
                ('reçu_par', models.CharField(blank=True, max_length=50, null=True)),
                ('quantité_émis', models.IntegerField(blank=True, default='0', null=True)),
                ('émis_par', models.CharField(blank=True, max_length=50, null=True)),
                ('émis_à', models.CharField(blank=True, max_length=50, null=True)),
                ('Tel_num', models.CharField(blank=True, max_length=50, null=True)),
                ('créé_par', models.CharField(blank=True, max_length=50, null=True)),
                ('niveau_de_réapprovisionnement', models.IntegerField(blank=True, default='0', null=True)),
                ('dernière_mise_à_jour', models.DateTimeField(auto_now=True)),
                ('exporter_au_format_CSV', models.BooleanField(default=False)),
                ('catégorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='G_STOCK.catégorie')),
            ],
        ),
    ]
