# Generated by Django 5.0.6 on 2024-06-16 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_STOCK', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='exporter_au_format_CSV',
        ),
        migrations.AlterField(
            model_name='stock',
            name='catégorie',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='G_STOCK.catégorie'),
        ),
    ]
