# Generated by Django 5.0.6 on 2024-06-16 17:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('G_STOCK', '0002_remove_stock_exporter_au_format_csv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='date_d_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
