# Generated by Django 5.0.6 on 2024-06-17 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('G_STOCK', '0005_stockhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='date',
        ),
    ]
